expr: syntax error: missing argument after ‘+’
MASTER_PORT: 
MASTER_ADDR: 
Traceback (most recent call last):
  File "/home/c-akshit/assn2/spring2024-assignment2-systems/cs336-systems/cs336_systems/distributed_multinode.py", line 109, in <module>
Traceback (most recent call last):
  File "/home/c-akshit/assn2/spring2024-assignment2-systems/cs336-systems/cs336_systems/distributed_multinode.py", line 109, in <module>
Traceback (most recent call last):
  File "/home/c-akshit/assn2/spring2024-assignment2-systems/cs336-systems/cs336_systems/distributed_multinode.py", line 109, in <module>
    main()
  File "/home/c-akshit/assn2/spring2024-assignment2-systems/cs336-systems/cs336_systems/distributed_multinode.py", line 102, in main
    main()
  File "/home/c-akshit/assn2/spring2024-assignment2-systems/cs336-systems/cs336_systems/distributed_multinode.py", line 102, in main
Traceback (most recent call last):
  File "/home/c-akshit/assn2/spring2024-assignment2-systems/cs336-systems/cs336_systems/distributed_multinode.py", line 109, in <module>
    multinode_distributed_demo(args=(args.data_size,
TypeError: multinode_distributed_demo() got an unexpected keyword argument 'args'
    main()
  File "/home/c-akshit/assn2/spring2024-assignment2-systems/cs336-systems/cs336_systems/distributed_multinode.py", line 102, in main
    multinode_distributed_demo(args=(args.data_size,
TypeError: multinode_distributed_demo() got an unexpected keyword argument 'args'
    main()
  File "/home/c-akshit/assn2/spring2024-assignment2-systems/cs336-systems/cs336_systems/distributed_multinode.py", line 102, in main
    multinode_distributed_demo(args=(args.data_size,
TypeError: multinode_distributed_demo() got an unexpected keyword argument 'args'
    multinode_distributed_demo(args=(args.data_size,
TypeError: multinode_distributed_demo() got an unexpected keyword argument 'args'
srun: error: ad12a3ca-01: tasks 0-1: Exited with exit code 1
srun: error: ad12a3ca-02: tasks 2-3: Exited with exit code 1
